COMPANIES = [
    "Google",
    "Microsoft",
    "Amazon",
    "Meta",
    "Apple",
    "NVIDIA",
    "Broadcom",
    "LinkedIn",
    "Databricks",
    "Rubrik",
    "Stripe",
    "Airbnb",
    "Uber",
    "Atlassian",
    "Snowflake",
    "Salesforce",
    "ServiceNow",
    "Confluent",
    "CrowdStrike",
    "Coinbase",
    "Cloudflare",
    "Datadog",
    "Adobe",
    "Qualcomm",
    "AMD",
    "Intel",
    "Cisco",
    "Oracle",
    "Walmart Global Tech",
    "Visa",
    "Mastercard",
    "PayPal",
    "JPMorgan Chase",
    "Goldman Sachs",
    "Morgan Stanley",
    "Bloomberg",
    "BlackRock",
    "Capital One",
    "American Express",
    "Zscaler",
    "Okta",
    "NetApp",
    "MongoDB",
    "Elastic",
    "Intuit",
    "Workday",
    "DocuSign",
    "Zoom",
    "Twilio",
    "GitLab",
    "HubSpot",
    "Freshworks",
    "UiPath",
    "Nutanix",
    "Cloudera",
    "Red Hat",
    "SAP Labs India",
    "Dell Technologies",
    "OpenText",
    "HashiCorp",
    "Akamai",
    "Splunk",
    "BrowserStack",
    "Postman",
    "PhonePe",
    "Razorpay",
    "Groww",
    "CRED",
    "Zepto",
    "Meesho",
    "Flipkart",
    "Swiggy",
    "Myntra",
    "Udaan",
    "BlackBuck",
    "Paytm",
    "PayU",
    "Pine Labs",
    "Cashfree Payments",
    "Zeta",
    "Navi Technologies",
    "Jupiter",
    "Juspay",
    "Moneyview",
    "RazorpayX",
    "Deutsche Bank",
    "Barclays",
    "UBS",
    "HSBC",
    "Wells Fargo",
    "Citi",
    "Bank of America",
    "Standard Chartered",
    "NatWest Group",
    "Societe Generale",
    "State Street",
    "S&P Global",
    "Target",
    "Lowe's",
    "ANZ",
    "Commonwealth Bank of Australia",
    "Synopsys",
    "Cadence Design Systems",
    "Arm",
    "MediaTek",
    "Motorola Solutions",
    "Samsung R&D Institute India",
    "Sony",
    "Panasonic",
    "Ericsson",
    "Nokia",
    "Bosch Global Software Technologies",
    "GE Vernova",
    "Fujitsu",
    "ZF",
    "Harman",
    "Mercedes-Benz R&D India",
    "BMW Group India",
    "Volvo Group",
    "Scania",
    "Deloitte",
    "EY",
    "PwC",
    "KPMG",
    "McKinsey & Company",
    "Mphasis",
    "EPAM Systems",
    "GlobalLogic",
    "Capgemini",
    "CGI",
    "DXC Technology",
    "Genpact",
    "EXL",
    "Virtusa",
    "Publicis Sapient",
    "Slalom",
    "Tiger Analytics",
    "Fractal Analytics",
    "Tredence",
    "Cartesian Consulting",
    "Sonata Software",
    "HashedIn by Deloitte",
    "LTIMindtree",
    "Coforge",
    "Swiggy Instamart",
    "ShareChat",
    "Moj",
    "Yellow.ai",
    "Observe.AI",
    "Sarvam AI",
    "Hasura",
    "Toast",
]
